import type { MatchErgebnis } from "@/types";

export const MOCK_MATCHES: MatchErgebnis[] = [
  {
    participantId: "mock-001",
    anzeigename: "Lea",
    age: 24,
    location: "Hamburg-Eimsbüttel",
    rolle: "suchend",
    gesamtScore: 91,
    band: "sehr passend",
    zusammenfassung:
      "Sehr ähnliches Stressbewältigungs­profil und deckungsgleiche Wohnvorstellungen.",
    komponenten: [
      { label: "Persönlichkeit", value: 94 },
      { label: "Motive", value: 89 },
      { label: "Werte", value: 95 },
      { label: "Wohlbefinden", value: 90 },
      { label: "Erwartungen", value: 91 },
      { label: "Lebensstil", value: 88 },
      { label: "Tagesrhythmus", value: 87 },
    ],
  },
  {
    participantId: "mock-002",
    anzeigename: "Jonas",
    age: 26,
    location: "Hamburg-Altona",
    rolle: "anbietend",
    gesamtScore: 85,
    band: "sehr passend",
    zusammenfassung:
      "Hohe Resilienz­übereinstimmung und gleiches Budget­niveau machen eine gute Basis.",
    komponenten: [
      { label: "Persönlichkeit", value: 82 },
      { label: "Motive", value: 86 },
      { label: "Werte", value: 83 },
      { label: "Wohlbefinden", value: 88 },
      { label: "Erwartungen", value: 82 },
      { label: "Lebensstil", value: 90 },
      { label: "Tagesrhythmus", value: 88 },
    ],
  },
  {
    participantId: "mock-003",
    anzeigename: "Mia",
    age: 23,
    location: "Hamburg-Wandsbek",
    rolle: "suchend",
    gesamtScore: 78,
    band: "gut passend",
    zusammenfassung:
      "Ähnliche Alltagsgewohnheiten; leichte Unterschiede beim Umgang mit Konflikten.",
    komponenten: [
      { label: "Persönlichkeit", value: 75 },
      { label: "Motive", value: 72 },
      { label: "Werte", value: 79 },
      { label: "Wohlbefinden", value: 77 },
      { label: "Erwartungen", value: 80 },
      { label: "Lebensstil", value: 84 },
      { label: "Tagesrhythmus", value: 71 },
    ],
  },
  {
    participantId: "mock-004",
    anzeigename: "Felix",
    age: 27,
    location: "Hamburg-Barmbek",
    rolle: "anbietend",
    gesamtScore: 74,
    band: "gut passend",
    zusammenfassung:
      "Geteilte Freizeitinteressen und Sauberkeits­vorstellungen; Budget leicht abweichend.",
    komponenten: [
      { label: "Persönlichkeit", value: 70 },
      { label: "Motive", value: 68 },
      { label: "Werte", value: 76 },
      { label: "Wohlbefinden", value: 72 },
      { label: "Erwartungen", value: 74 },
      { label: "Lebensstil", value: 78 },
      { label: "Tagesrhythmus", value: 73 },
    ],
  },
  {
    participantId: "mock-005",
    anzeigename: "Sara",
    age: 22,
    location: "Hamburg-Wandsbek",
    rolle: "suchend",
    gesamtScore: 68,
    band: "gut passend",
    zusammenfassung:
      "Komplementäre Tagesrhythmen; unterschiedliche Schlafzeiten könnten Absprache erfordern.",
    komponenten: [
      { label: "Persönlichkeit", value: 65 },
      { label: "Motive", value: 63 },
      { label: "Werte", value: 74 },
      { label: "Wohlbefinden", value: 66 },
      { label: "Erwartungen", value: 58 },
      { label: "Lebensstil", value: 62 },
      { label: "Tagesrhythmus", value: 80 },
    ],
  },
  {
    participantId: "mock-006",
    anzeigename: "Tobias",
    age: 25,
    location: "Norderstedt",
    rolle: "anbietend",
    gesamtScore: 54,
    band: "mäßig passend",
    zusammenfassung:
      "Grundlegende Wohnvorstellungen stimmen überein; Lifestyle-Unterschiede sollten besprochen werden.",
    komponenten: [
      { label: "Persönlichkeit", value: 50 },
      { label: "Motive", value: 52 },
      { label: "Werte", value: 61 },
      { label: "Wohlbefinden", value: 55 },
      { label: "Erwartungen", value: 53 },
      { label: "Lebensstil", value: 48 },
      { label: "Tagesrhythmus", value: 57 },
    ],
  },
];
